src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $story = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column(length: 255)]
    private ?string $publish_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStory(): ?string
    {
        return $this->story;
    }

    public function setStory(string $story): self
    {
        $this->story = $story;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getPublishDate(): ?string
    {
        return $this->publish_date;
    }

    public function setPublishDate(string $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }
}

src/Controller/NavController.php
<?php

namespace App\Controller;

use App\Repository\ArticlesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Json;

class NavController extends AbstractController
{
    #[Route('/article/top10', name: 'app_top10_articles')]
    public function showTopTenArticles(ArticlesRepository $article): JsonResponse
    {
        $response = $article->topTen();
        return $this->json($response);
    }

    #[Route('/article/randomtopics', name: 'app_article_topics')]
    public function showRandomArtleTopics(ArticlesRepository $article): JsonResponse
    {
        $response = $article->newsTopics();
        return $this->json($response);
    }

    #[Route('/home', name: 'app_nav_home')]
    public function home(ArticlesRepository $articlesRepository): Response
    {
        $articles = $articlesRepository;

        $navbar = ['home', 'about', 'news', 'trend'];
        
        return $this->render("nav/home.html.twig",
            array('navTitle' => $navbar,
                // 'topic' => $topics,
                'topic' => $articles->findAll(),
                // 'news' => $upcomingNews,
            )
        );
    }

    #[Route('/about', name: 'app_nav_about')]
    public function about(): Response
    {
        $navbar = ['home', 'about', 'news', 'trend'];

        return $this->render("nav/about.html.twig",
            array('navTitle' => $navbar));
    }

    #[Route('/article/stories', name: 'app_article_stories')]
    public function findStoryArticles(ArticlesRepository $article): JsonResponse
    {
        $response = $article->findStoryArticles();
        return $this->json($response);
    }

    #[Route('/news/{slug}', name: 'app_nav_news')]
    public function news(ArticlesRepository $articlesRepository, $slug=null): Response
    {
        $articles = $articlesRepository;
        $navbar = ['home', 'about', 'news', 'trend'];
        $category = $slug;

        if($slug){
            return $this->render("nav/category.html.twig",
                array('navTitle' => $navbar,
                'topic' => $articles->findAll(),                
                'category' => $category,
            ));
        }else{
            return $this->render("nav/news.html.twig",
                array('navTitle' => $navbar,
                // 'topic' => $articles->findAll(),
            ));
        }
    }


    #[Route('/trend', name: 'app_nav_trend')]
    public function trend(): Response
    {
        $navbar = ['home', 'about', 'news', 'trend'];

        return $this->render("nav/trend.html.twig",
            array('navTitle' => $navbar));
    }
}

templates/nav/about.html.twig
{% extends "base.html.twig" %}

{% block body %}
    
<div class="mx-3">
    <h1>About Page Template</h1>
</div>

{% endblock %}

templates/nav/category.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <h1>Slug: {{ category }} </h1>

    <div class="container">
        {% for ele in topic %}
        
            {% if ele.id == category  %}
                <h1>Category: {{ ele.category }} </h1>
                <h3>{{ ele.title|upper }}</h3>
                <div class="border row">
                    <img class="col-3" src="\images\{{ ele.image }}" alt="">
                    <p class="col-7">{{ ele.story }} </p>
                </div>
                <div class="text-end"><em> - {{ ele.author }} </em></div>
            {% endif %}
                    
        {% endfor %}
        <p></p>
    </div>



{% endblock %}

templates/nav/home.html.twig
{% extends "base.html.twig" %}

{% block body %}

<div class="container-fluid mt-4">
    <div class="d-flex justify-content-between mx-2">
        <div class="headline col-7 px-2">
            <div>
                <img class="homeImg">
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h2 class="col-4 fw-bold fs-1">The Bright Future of Web 2023</h2>
                <div class="col-6">
                    <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Iaculis at erat pellentesque adipiscing. Cras sed felis eget velit aliquet sagittis id consectetur purus.
                    </p>
                    <div class="d-grid gap-2 col-10">
                        <button class="btn btn-primary">
                            <a class="text-light" style="text-decoration: none" href="{{ path('create_article') }}">Make an article</a>
                        </button>
                    </div>
                </div>
            </div>
        
        </div>
        <div class="col-4 bg-dark text-light">
            <div class="newTopics px-2">
                <h3 class="text-warning mt-2 mb-">New</h3>
                <div id='topTenArticles' style="height:380px; overflow-y:auto">                    
                </div>
            </div>
        </div>
    </div>
</div>

<div id="randomArticleTopics" class="mt-5 mx-4 d-flex justify-content-between" style="width: 96vw; overflow-x:auto">

    {% for new in topic %}
        <div class="col-3 d-flex flex-wrap">
            <img class="me-2" src="\images\{{ new.image }}" width="125" height="150" alt="">
            <div style="width: 120px; height:155px; overflow:hidden">
                <h5>{{ new.title }}</h5>
                <p>{{ new.story }}</p>
            </div>
        </div>
    {% endfor %}
</div>

<script src="{{ asset('js/topTenArticles.js')}}"></script>
{# <script src="{{ asset('js/newsTopics.js')}}"></script> #}

{% endblock %}

templates/nav/news.html.twig
{% extends "base.html.twig" %}

{% block body %}
    
<div class="mx-3">
    <h1>News Page Template</h1>
</div>

<div class="bg-secondary bg-opacity-10 container-fluid px-4">
    <div class="d-flex justify-content-between">

        <div id="new_topics" class="col-7">

            {# {% for char in topic %}                
                <div class="my-4 px-4 py-2 bg-light" style="box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;">
                    <h3 class="">{{ char.title }}</h3>
                    <div style="border:1px solid green; margin-bottom: 7px;"></div>
                    <div class="d-flex px-2 justify-content-between">
                        <p class="pe-2"><img src="images/person-fill.svg" alt="">Posted By: {{ char.author }} 
                        </p>
                        <p class="pe-2">
                        <img src="images/clock-fill.svg" alt="">
                        {{ char.publishDate }} 
                        </p>
                        <p class="pe-2">
                            <span class="badge text-warning" style="margin-top:3px; position:absolute; top:80;left:818">
                            4</span> 
                            <img src="images/heart-fill.svg" alt="">
                            Likes
                        </p>
                    </div>
                    <div style="border:1px solid green; margin-top:0; margin-bottom:5px"></div>
                    <div class="d-flex flex-wrap">
                        <div class="me-3">
                            <img style="border:2px solid black;" src="\images\{{ char.image }}" height="150" alt="">
                        </div>
                        <p class="px-2 col-7" style="width: 35vw; height:155px; overflow:hidden"> {{ char.story }}.</p>
                    </div>
                    <div class="d-flex justify-content-between mt-2">
                    <div class="">
                        <p> Category: {{ char.category }} </p>
                    </div>
                        <div>
                            <button class="btn btn-info text-light "><a href="/news/{{ char.id }}" style="text-decoration:none; color:white">Continue Reading</a></button>
                        </div>
                    </div>
                </div>  
            {% endfor %}
                 #}
        </div>

        <div class="col-4 my-4">
            
            <div class="border p-2 bg-light input-group mb-3" style="box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;">
                <input type="text" class="form-control bg-secondary bg-opacity-10">
                <button class="btn btn-info text-light" type="button">Search</button>
            </div>
            <div>
                <div class="border mb-1 p-2" style="height: 50px; box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;">
                    <h5>Feature Posts</h5>
                </div>

                <div class="border p-2 bg-light" style="box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;">
                    <div class="border" style="height:190px">
                        <img src="" alt="pic">
                    </div>
                    
                    <div class="border bg-info bg-opacity-75 text-light">
                        <h4 class="p-1">Title</h4>
                        <p class="p-1">
                        Ut sem nulla pharetra diam sit amet. Pharetra vel turpis nunc eget lorem dolor sed. Porta lorem mollis aliquam ut porttitor leo. Egestas dui id ornare arcu odio ut sem nulla pharetra.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{{ asset('js/storyArticles.js')}}"></script>
{% endblock %}

templates/nav/trend.html.twig
{% extends "base.html.twig" %}

{% block body %}
    
<div class="mx-3">
    <h1>Trend Page Template</h1>
</div>

{% endblock %}